# name: Deployment

# on:
#   workflow_dispatch : 

# jobs:

#   build-and-deploy:
#     permissions:
#       id-token: write # This is required for requesting the JWT
#       contents: write

#     name:  Deployment
#     # if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     env:
#       DIST: build
#       BUCKET: frontend-the-debuggers
#       AWS_REGION: ap-south-1
#       DIST_ID: E1JIL1PSKXTWIP
#       S3_CLOUDFRONT_ORIGIN_NAME: frontend-the-debuggers.s3.ap-south-1.amazonaws.com	
#       CI: false

#     steps:
#     - name: Code Checkout
#       uses: actions/checkout@v3

    
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}


#     - name: Setting up Node
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16.18.1'

#     - name: Install Dependencies
#       run: |
#         node --version
#         npm install

#     - name: Build Static Website
#       run: | 
#         npm run build

#     - name: Sync Build with S3 bucket
#       run: |
#         aws s3 sync ${{ env.DIST }} s3://${{ env.BUCKET }}


#     - name: Creating new Cloudfront Invalidation
#       run: |

#         aws cloudfront create-invalidation \
#           --distribution-id ${{ env.DIST_ID }} \
#           --paths "/*" --region ${{ env.AWS_REGION }}

name: UE1-PROD-DEPLOY-2025.08

on:
  workflow_dispatch : 

jobs:

  build-and-deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write

    name:  UE1-PROD-DEPLOY-2025.08-${{ github.run_number }}
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DIST: build
      BUCKET: frontend-the-debuggers
      AWS_REGION: ap-south-1
      DIST_ID: E1JIL1PSKXTWIP
      S3_CLOUDFRONT_ORIGIN_NAME: frontend-the-debuggers.s3.ap-south-1.amazonaws.com	
      CI: false

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3


    - name: Setting up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.18.1'

    - name: Install Dependencies
      run: |
        node --version
        npm install

    - name: Build Static Website
      run: | 
        npm run build

      

